-- Inserção de Produtos
INSERT INTO products (id, product_name, category_id) VALUES (1, 'iPhone 14 Pro', 1);
INSERT INTO products (id, product_name, category_id) VALUES (2, 'Dyson V11 Vacuum', 2);
INSERT INTO products (id, product_name, category_id) VALUES (3, 'Levi''s 501 Jeans', 3);
INSERT INTO products (id, product_name, category_id) VALUES (4, 'The Da Vinci Code', 4);
INSERT INTO products (id, product_name, category_id) VALUES (5, 'Neutrogena Skincare Set', 5);
INSERT INTO products (id, product_name, category_id) VALUES (6, 'Wilson Evolution Basketball', 6);
INSERT INTO products (id, product_name, category_id) VALUES (7, 'MacBook Pro 16-inch', 1);
INSERT INTO products (id, product_name, category_id) VALUES (8, 'Blueair Classic 480i', 2);
INSERT INTO products (id, product_name, category_id) VALUES (9, 'Nike Air Force 1', 3);
INSERT INTO products (id, product_name, category_id) VALUES (10, 'Dune by Frank Herbert', 4);
INSERT INTO products (id, product_name, category_id) VALUES (11, 'Chanel No. 5 Perfume', 5);
INSERT INTO products (id, product_name, category_id) VALUES (12, 'Babolat Pure Drive Tennis Racket', 6);
INSERT INTO products (id, product_name, category_id) VALUES (13, 'Samsung Galaxy Tab S8', 1);
INSERT INTO products (id, product_name, category_id) VALUES (14, 'Keurig K-Elite Coffee Maker', 2);
INSERT INTO products (id, product_name, category_id) VALUES (15, 'North Face Down Jacket', 3);
INSERT INTO products (id, product_name, category_id) VALUES (16, 'Salt, Fat, Acid, Heat by Samin Nosrat', 4);
INSERT INTO products (id, product_name, category_id) VALUES (17, 'Dyson Supersonic Hair Dryer', 5);
INSERT INTO products (id, product_name, category_id) VALUES (18, 'Manduka PRO Yoga Mat', 6);
INSERT INTO products (id, product_name, category_id) VALUES (19, 'Garmin Forerunner 945', 1);
INSERT INTO products (id, product_name, category_id) VALUES (20, 'Ninja Professional Blender', 2);
INSERT INTO products (id, product_name, category_id) VALUES (21, 'Zara Summer Dress', 3);
INSERT INTO products (id, product_name, category_id) VALUES (22, 'Gone Girl by Gillian Flynn', 4);
INSERT INTO products (id, product_name, category_id) VALUES (23, 'Olay Regenerist Face Cream', 5);
INSERT INTO products (id, product_name, category_id) VALUES (24, 'Adidas FIFA World Cup Football', 6);
INSERT INTO products (id, product_name, category_id) VALUES (25, 'Bose QuietComfort 35 Headphones', 1);
INSERT INTO products (id, product_name, category_id) VALUES (26, 'Panasonic NN-SN966S Microwave', 2);
INSERT INTO products (id, product_name, category_id) VALUES (27, 'Adidas Ultraboost Shoes', 3);
INSERT INTO products (id, product_name, category_id) VALUES (28, 'Pride and Prejudice by Jane Austen', 4);
INSERT INTO products (id, product_name, category_id) VALUES (29, 'MAC Ruby Woo Lipstick', 5);
INSERT INTO products (id, product_name, category_id) VALUES (30, 'Nike Air Zoom Pegasus 37', 6);
INSERT INTO products (id, product_name, category_id) VALUES (31, 'Sony WH-1000XM4 Headphones', 1);
INSERT INTO products (id, product_name, category_id) VALUES (32, 'Instant Pot Duo', 2);
INSERT INTO products (id, product_name, category_id) VALUES (33, 'Under Armour HeatGear T-Shirt', 3);
INSERT INTO products (id, product_name, category_id) VALUES (34, '1984 by George Orwell', 4);
INSERT INTO products (id, product_name, category_id) VALUES (35, 'L''Oreal Revitalift Serum', 5);
INSERT INTO products (id, product_name, category_id) VALUES (36, 'Peloton Bike', 6);
INSERT INTO products (id, product_name, category_id) VALUES (37, 'Apple Watch Series 8', 1);
INSERT INTO products (id, product_name, category_id) VALUES (38, 'Roomba i7+', 2);
INSERT INTO products (id, product_name, category_id) VALUES (39, 'Columbia Fleece Jacket', 3);
INSERT INTO products (id, product_name, category_id) VALUES (40, 'Harry Potter and the Sorcerer''s Stone', 4);
INSERT INTO products (id, product_name, category_id) VALUES (41, 'Estee Lauder Advanced Night Repair', 5);
INSERT INTO products (id, product_name, category_id) VALUES (42, 'Fitbit Charge 5', 6);
INSERT INTO products (id, product_name, category_id) VALUES (43, 'GoPro HERO10 Black', 1);
INSERT INTO products (id, product_name, category_id) VALUES (44, 'Nespresso VertuoPlus', 2);
INSERT INTO products (id, product_name, category_id) VALUES (45, 'Patagonia Better Sweater', 3);
INSERT INTO products (id, product_name, category_id) VALUES (46, 'Becoming by Michelle Obama', 4);
INSERT INTO products (id, product_name, category_id) VALUES (47, 'Clinique Moisture Surge', 5);
INSERT INTO products (id, product_name, category_id) VALUES (48, 'Yeti Rambler Tumbler', 6);
INSERT INTO products (id, product_name, category_id) VALUES (49, 'Kindle Paperwhite', 1);
INSERT INTO products (id, product_name, category_id) VALUES (50, 'Breville Smart Oven', 2);
INSERT INTO products (id, product_name, category_id) VALUES (51, 'Ray-Ban Aviator Sunglasses', 3);
INSERT INTO products (id, product_name, category_id) VALUES (52, 'The Silent Patient by Alex Michaelides', 4);
INSERT INTO products (id, product_name, category_id) VALUES (53, 'Shiseido Ultimate Sun Protector', 5);
INSERT INTO products (id, product_name, category_id) VALUES (54, 'Titleist Pro V1 Golf Balls', 6);
INSERT INTO products (id, product_name, category_id) VALUES (55, 'Anker PowerCore Portable Charger', 1);
INSERT INTO products (id, product_name, category_id) VALUES (56, 'KitchenAid Artisan Stand Mixer', 2);
INSERT INTO products (id, product_name, category_id) VALUES (57, 'Calvin Klein Boxer Briefs', 3);
INSERT INTO products (id, product_name, category_id) VALUES (58, 'Educated by Tara Westover', 4);
INSERT INTO products (id, product_name, category_id) VALUES (59, 'Anastasia Beverly Hills Brow Wiz', 5);
INSERT INTO products (id, product_name, category_id) VALUES (60, 'Hyperice Hypervolt Massager', 6);
INSERT INTO products (id, product_name, category_id) VALUES (61, 'Nintendo Switch', 1);
INSERT INTO products (id, product_name, category_id) VALUES (62, 'Philips Airfryer XXL', 2);
INSERT INTO products (id, product_name, category_id) VALUES (63, 'Hanes ComfortSoft T-Shirt', 3);
INSERT INTO products (id, product_name, category_id) VALUES (64, 'Where the Crawdads Sing by Delia Owens', 4);
INSERT INTO products (id, product_name, category_id) VALUES (65, 'Lancome La Vie Est Belle', 5);
INSERT INTO products (id, product_name, category_id) VALUES (66, 'Garmin Edge 530', 6);
INSERT INTO products (id, product_name, category_id) VALUES (67, 'Samsung QLED 4K TV', 1);
INSERT INTO products (id, product_name, category_id) VALUES (68, 'Eufy RoboVac 11S', 2);
INSERT INTO products (id, product_name, category_id) VALUES (69, 'Puma Suede Classic Sneakers', 3);
INSERT INTO products (id, product_name, category_id) VALUES (70, 'The Great Gatsby by F. Scott Fitzgerald', 4);
INSERT INTO products (id, product_name, category_id) VALUES (71, 'Drunk Elephant C-Firma Day Serum', 5);
INSERT INTO products (id, product_name, category_id) VALUES (72, 'Nike Metcon 6', 6);
INSERT INTO products (id, product_name, category_id) VALUES (73, 'HP Spectre x360 Laptop', 1);
INSERT INTO products (id, product_name, category_id) VALUES (74, 'De''Longhi Magnifica Espresso Machine', 2);
INSERT INTO products (id, product_name, category_id) VALUES (75, 'Tommy Hilfiger Polo Shirt', 3);
INSERT INTO products (id, product_name, category_id) VALUES (76, 'To Kill a Mockingbird by Harper Lee', 4);
INSERT INTO products (id, product_name, category_id) VALUES (77, 'Glossier Boy Brow', 5);
INSERT INTO products (id, product_name, category_id) VALUES (78, 'Rogue Fitness Kettlebell', 6);
INSERT INTO products (id, product_name, category_id) VALUES (79, 'Apple AirPods Pro', 1);
INSERT INTO products (id, product_name, category_id) VALUES (80, 'Dyson Pure Cool Link', 2);
INSERT INTO products (id, product_name, category_id) VALUES (81, 'Levi''s Trucker Jacket', 3);
INSERT INTO products (id, product_name, category_id) VALUES (82, 'The Hobbit by J.R.R. Tolkien', 4);
INSERT INTO products (id, product_name, category_id) VALUES (83, 'Charlotte Tilbury Magic Cream', 5);
INSERT INTO products (id, product_name, category_id) VALUES (84, 'Spalding NBA Street Basketball', 6);
INSERT INTO products (id, product_name, category_id) VALUES (85, 'Ring Video Doorbell', 1);
INSERT INTO products (id, product_name, category_id) VALUES (86, 'LG OLED TV', 2);
INSERT INTO products (id, product_name, category_id) VALUES (87, 'Uniqlo Ultra Light Down Jacket', 3);
INSERT INTO products (id, product_name, category_id) VALUES (88, 'The Catcher in the Rye by J.D. Salinger', 4);
INSERT INTO products (id, product_name, category_id) VALUES (89, 'Sunday Riley Good Genes', 5);
INSERT INTO products (id, product_name, category_id) VALUES (90, 'On Running Cloud Shoes', 6);
INSERT INTO products (id, product_name, category_id) VALUES (91, 'Logitech MX Master 3 Mouse', 1);
INSERT INTO products (id, product_name, category_id) VALUES (92, 'Instant Pot Duo Crisp', 2);
INSERT INTO products (id, product_name, category_id) VALUES (93, 'Adidas Originals Superstar Sneakers', 3);
INSERT INTO products (id, product_name, category_id) VALUES (94, 'The Alchemist by Paulo Coelho', 4);
INSERT INTO products (id, product_name, category_id) VALUES (95, 'Tatcha The Water Cream', 5);
INSERT INTO products (id, product_name, category_id) VALUES (96, 'Garmin Fenix 6X Pro', 6);
INSERT INTO products (id, product_name, category_id) VALUES (97, 'Bose SoundLink Revolve+ Speaker', 1);
INSERT INTO products (id, product_name, category_id) VALUES (98, 'Vitamix Explorian Blender', 2);
INSERT INTO products (id, product_name, category_id) VALUES (99, 'Gap Essential Crewneck T-Shirt', 3);
INSERT INTO products (id, product_name, category_id) VALUES (100, 'The Power of Now by Eckhart Tolle', 4);
INSERT INTO products (id, product_name, category_id) VALUES (101, 'Kiehl''s Midnight Recovery Concentrate', 5);
INSERT INTO products (id, product_name, category_id) VALUES (102, 'Under Armour HOVR Sonic 4 Shoes', 6);
INSERT INTO products (id, product_name, category_id) VALUES (103, 'Canon EOS R5 Camera', 1);
INSERT INTO products (id, product_name, category_id) VALUES (104, 'Shark IQ Robot Vacuum', 2);
INSERT INTO products (id, product_name, category_id) VALUES (105, 'H&M Slim Fit Jeans', 3);
INSERT INTO products (id, product_name, category_id) VALUES (106, 'The Girl on the Train by Paula Hawkins', 4);
INSERT INTO products (id, product_name, category_id) VALUES (107, 'The Ordinary Niacinamide Serum', 5);
INSERT INTO products (id, product_name, category_id) VALUES (108, 'Bowflex SelectTech 552 Dumbbells', 6);
INSERT INTO products (id, product_name, category_id) VALUES (109, 'Google Nest Hub Max', 1);
INSERT INTO products (id, product_name, category_id) VALUES (110, 'Cuisinart Griddler Deluxe', 2);
INSERT INTO products (id, product_name, category_id) VALUES (111, 'Old Navy Relaxed-Fit T-Shirt', 3);
INSERT INTO products (id, product_name, category_id) VALUES (112, 'Sapiens: A Brief History of Humankind by Yuval Noah Harari', 4);
INSERT INTO products (id, product_name, category_id) VALUES (113, 'Biore UV Aqua Rich Watery Essence Sunscreen', 5);
INSERT INTO products (id, product_name, category_id) VALUES (114, 'Fitbit Versa 3', 6);
INSERT INTO products (id, product_name, category_id) VALUES (115, 'Amazon Echo Show 10', 1);
INSERT INTO products (id, product_name, category_id) VALUES (116, 'Breville Smart Grill', 2);
INSERT INTO products (id, product_name, category_id) VALUES (117, 'Gap High Rise Skinny Jeans', 3);
INSERT INTO products (id, product_name, category_id) VALUES (118, 'Atomic Habits by James Clear', 4);
INSERT INTO products (id, product_name, category_id) VALUES (119, 'CeraVe Hydrating Facial Cleanser', 5);
INSERT INTO products (id, product_name, category_id) VALUES (120, 'YETI Hopper Flip Portable Cooler', 6);
INSERT INTO products (id, product_name, category_id) VALUES (121, 'Apple iPad Air', 1);
INSERT INTO products (id, product_name, category_id) VALUES (122, 'Hamilton Beach FlexBrew Coffee Maker', 2);
INSERT INTO products (id, product_name, category_id) VALUES (123, 'Forever 21 Graphic Tee', 3);
INSERT INTO products (id, product_name, category_id) VALUES (124, 'The Subtle Art of Not Giving a F*ck by Mark Manson', 4);
INSERT INTO products (id, product_name, category_id) VALUES (125, 'NARS Radiant Creamy Concealer', 5);
INSERT INTO products (id, product_name, category_id) VALUES (126, 'Yeti Roadie 24 Cooler', 6);
INSERT INTO products (id, product_name, category_id) VALUES (127, 'Sony PlayStation 5', 1);
INSERT INTO products (id, product_name, category_id) VALUES (128, 'Dyson Supersonic Hair Dryer', 2);
INSERT INTO products (id, product_name, category_id) VALUES (129, 'Lululemon Align Leggings', 3);
INSERT INTO products (id, product_name, category_id) VALUES (130, 'The Four Agreements by Don Miguel Ruiz', 4);
INSERT INTO products (id, product_name, category_id) VALUES (131, 'Fenty Beauty Killawatt Highlighter', 5);
INSERT INTO products (id, product_name, category_id) VALUES (132, 'Hydro Flask Wide Mouth Water Bottle', 6);
INSERT INTO products (id, product_name, category_id) VALUES (133, 'Microsoft Surface Laptop 4', 1);
INSERT INTO products (id, product_name, category_id) VALUES (134, 'Keurig K-Mini Coffee Maker', 2);
INSERT INTO products (id, product_name, category_id) VALUES (135, 'Gap Crewneck Sweatshirt', 3);
INSERT INTO products (id, product_name, category_id) VALUES (136, 'Think and Grow Rich by Napoleon Hill', 4);
INSERT INTO products (id, product_name, category_id) VALUES (137, 'The Ordinary Hyaluronic Acid Serum', 5);
INSERT INTO products (id, product_name, category_id) VALUES (138, 'Fitbit Inspire 2', 6);
INSERT INTO products (id, product_name, category_id) VALUES (139, 'Samsung Odyssey G9 Gaming Monitor', 1);
INSERT INTO products (id, product_name, category_id) VALUES (140, 'Instant Pot Ultra', 2);
INSERT INTO products (id, product_name, category_id) VALUES (141, 'Adidas Essential Track Pants', 3);
INSERT INTO products (id, product_name, category_id) VALUES (142, 'The Power of Habit by Charles Duhigg', 4);
INSERT INTO products (id, product_name, category_id) VALUES (143, 'Clinique Dramatically Different Moisturizing Lotion', 5);
INSERT INTO products (id, product_name, category_id) VALUES (144, 'YETI Tundra 45 Cooler', 6);
INSERT INTO products (id, product_name, category_id) VALUES (145, 'Apple AirPods Max', 1);
INSERT INTO products (id, product_name, category_id) VALUES (146, 'Cuisinart Coffee Center', 2);
INSERT INTO products (id, product_name, category_id) VALUES (147, 'Levi''s Sherpa Trucker Jacket', 3);
INSERT INTO products (id, product_name, category_id) VALUES (148, 'The Outsiders by S.E. Hinton', 4);
INSERT INTO products (id, product_name, category_id) VALUES (149, 'Laneige Water Sleeping Mask', 5);
INSERT INTO products (id, product_name, category_id) VALUES (150, 'Bose SoundSport Wireless Earbuds', 6);
INSERT INTO products (id, product_name, category_id) VALUES (151, 'Ninja Foodi Pressure Cooker', 2);
INSERT INTO products (id, product_name, category_id) VALUES (152, 'Nike Sportswear Club Fleece Hoodie', 3);
INSERT INTO products (id, product_name, category_id) VALUES (153, 'The Night Circus by Erin Morgenstern', 4);
INSERT INTO products (id, product_name, category_id) VALUES (154, 'GlamGlow Supermud Clearing Treatment', 5);
INSERT INTO products (id, product_name, category_id) VALUES (155, 'Garmin Forerunner 245', 6);
INSERT INTO products (id, product_name, category_id) VALUES (156, 'Google Pixel 6 Pro', 1);
INSERT INTO products (id, product_name, category_id) VALUES (157, 'Breville Nespresso Creatista Plus', 2);
INSERT INTO products (id, product_name, category_id) VALUES (158, 'Under Armour Tech 2.0 T-Shirt', 3);
INSERT INTO products (id, product_name, category_id) VALUES (159, 'The Art of War by Sun Tzu', 4);
INSERT INTO products (id, product_name, category_id) VALUES (160, 'Youth to the People Superfood Antioxidant Cleanser', 5);
INSERT INTO products (id, product_name, category_id) VALUES (161, 'TriggerPoint GRID Foam Roller', 6);
INSERT INTO products (id, product_name, category_id) VALUES (162, 'Apple MacBook Air', 1);
INSERT INTO products (id, product_name, category_id) VALUES (163, 'Cuisinart Custom 14-Cup Food Processor', 2);
INSERT INTO products (id, product_name, category_id) VALUES (164, 'Adidas 3-Stripes Shorts', 3);
INSERT INTO products (id, product_name, category_id) VALUES (165, 'The Hunger Games by Suzanne Collins', 4);
INSERT INTO products (id, product_name, category_id) VALUES (166, 'Neutrogena Hydro Boost Water Gel', 5);
INSERT INTO products (id, product_name, category_id) VALUES (167, 'Yeti Rambler Bottle', 6);
INSERT INTO products (id, product_name, category_id) VALUES (168, 'Samsung Odyssey G7 Gaming Monitor', 1);
INSERT INTO products (id, product_name, category_id) VALUES (169, 'Instant Pot Duo Evo Plus', 2);
INSERT INTO products (id, product_name, category_id) VALUES (170, 'Nike Tempo Running Shorts', 3);
INSERT INTO products (id, product_name, category_id) VALUES (171, 'The Girl with the Dragon Tattoo by Stieg Larsson', 4);
INSERT INTO products (id, product_name, category_id) VALUES (172, 'Paula''s Choice Skin Perfecting 2% BHA Liquid Exfoliant', 5);
INSERT INTO products (id, product_name, category_id) VALUES (173, 'Bowflex SelectTech 1090 Adjustable Dumbbells', 6);
INSERT INTO products (id, product_name, category_id) VALUES (174, 'Amazon Fire TV Stick 4K', 1);
INSERT INTO products (id, product_name, category_id) VALUES (175, 'Crock-Pot 6-Quart Slow Cooker', 2);
INSERT INTO products (id, product_name, category_id) VALUES (176, 'Uniqlo Airism Mesh Boxer Briefs', 3);
INSERT INTO products (id, product_name, category_id) VALUES (177, 'The Sun Also Rises by Ernest Hemingway', 4);
INSERT INTO products (id, product_name, category_id) VALUES (178, 'First Aid Beauty Ultra Repair Cream', 5);
INSERT INTO products (id, product_name, category_id) VALUES (179, 'Oakley Holbrook Sunglasses', 6);
INSERT INTO products (id, product_name, category_id) VALUES (180, 'Google Pixelbook Go', 1);
INSERT INTO products (id, product_name, category_id) VALUES (181, 'Dyson V8 Absolute', 2);
INSERT INTO products (id, product_name, category_id) VALUES (182, 'Levi''s 511 Slim Fit Jeans', 3);
INSERT INTO products (id, product_name, category_id) VALUES (183, 'The Martian by Andy Weir', 4);
INSERT INTO products (id, product_name, category_id) VALUES (184, 'La Mer Crème de la Mer Moisturizer', 5);
INSERT INTO products (id, product_name, category_id) VALUES (185, 'Polar Vantage V2', 6);
INSERT INTO products (id, product_name, category_id) VALUES (186, 'Sonos Beam Soundbar', 1);
INSERT INTO products (id, product_name, category_id) VALUES (187, 'Anova Precision Cooker', 2);
INSERT INTO products (id, product_name, category_id) VALUES (188, 'Nike Dri-FIT Training Shorts', 3);
INSERT INTO products (id, product_name, category_id) VALUES (189, 'Glossier Cloud Paint', 5);
INSERT INTO products (id, product_name, category_id) VALUES (190, 'TRX All-in-One Suspension Training System', 6);
INSERT INTO products (id, product_name, category_id) VALUES (191, 'Logitech G Pro X Wireless Gaming Headset', 1);
INSERT INTO products (id, product_name, category_id) VALUES (192, 'Breville Smart Coffee Grinder Pro', 2);
INSERT INTO products (id, product_name, category_id) VALUES (193, 'Adidas Ultraboost Running Shoes', 3);
INSERT INTO products (id, product_name, category_id) VALUES (194, 'The Road by Cormac McCarthy', 4);
INSERT INTO products (id, product_name, category_id) VALUES (195, 'Tom Ford Black Orchid Perfume', 5);
INSERT INTO products (id, product_name, category_id) VALUES (196, 'GoPro HERO9 Black', 6);
INSERT INTO products (id, product_name, category_id) VALUES (197, 'Apple TV 4K', 1);
INSERT INTO products (id, product_name, category_id) VALUES (198, 'Instant Pot Duo Nova', 2);
INSERT INTO products (id, product_name, category_id) VALUES (199, 'Gap 1969 Original Fit Jeans', 3);
INSERT INTO products (id, product_name, category_id) VALUES (200, 'The Goldfinch by Donna Tartt', 4);
INSERT INTO products (id, product_name, category_id) VALUES (201, 'Dr. Jart+ Cicapair Tiger Grass Color Correcting Treatment', 5);
INSERT INTO products (id, product_name, category_id) VALUES (202, 'Yeti Tundra Haul Portable Wheeled Cooler', 6);
INSERT INTO products (id, product_name, category_id) VALUES (203, 'Samsung Galaxy Watch 4', 1);
INSERT INTO products (id, product_name, category_id) VALUES (204, 'KitchenAid Stand Mixer', 2);
INSERT INTO products (id, product_name, category_id) VALUES (205, 'Lululemon Wunder Under High-Rise Leggings', 3);
INSERT INTO products (id, product_name, category_id) VALUES (206, 'The Great Alone by Kristin Hannah', 4);
INSERT INTO products (id, product_name, category_id) VALUES (207, 'Caudalie Vinoperfect Radiance Serum', 5);
INSERT INTO products (id, product_name, category_id) VALUES (208, 'Bose SoundLink Color Bluetooth Speaker II', 6);
INSERT INTO products (id, product_name, category_id) VALUES (209, 'Canon EOS Rebel T7i DSLR Camera', 1);
INSERT INTO products (id, product_name, category_id) VALUES (210, 'Uniqlo Airism Seamless Boxer Briefs', 3);
INSERT INTO products (id, product_name, category_id) VALUES (211, 'L''Occitane Shea Butter Hand Cream', 5);
INSERT INTO products (id, product_name, category_id) VALUES (212, 'YETI Tundra 65 Cooler', 6);
INSERT INTO products (id, product_name, category_id) VALUES (213, 'Apple MacBook Pro 16-inch', 1);
INSERT INTO products (id, product_name, category_id) VALUES (214, 'iRobot Braava Jet M6', 2);
INSERT INTO products (id, product_name, category_id) VALUES (215, 'Champion Reverse Weave Hoodie', 3);
INSERT INTO products (id, product_name, category_id) VALUES (216, 'The Nightingale by Kristin Hannah', 4);
INSERT INTO products (id, product_name, category_id) VALUES (217, 'Tarte Shape Tape Concealer', 5);
INSERT INTO products (id, product_name, category_id) VALUES (218, 'Garmin Forerunner 945', 6);
INSERT INTO products (id, product_name, category_id) VALUES (219, 'Amazon Echo Dot (4th Gen)', 1);
INSERT INTO products (id, product_name, category_id) VALUES (220, 'Philips Sonicare DiamondClean Toothbrush', 2);
INSERT INTO products (id, product_name, category_id) VALUES (221, 'Old Navy Mid-Rise Rockstar Super Skinny Jeans', 3);
INSERT INTO products (id, product_name, category_id) VALUES (222, 'The Ordinary Caffeine Solution 5% + EGCG', 5);
INSERT INTO products (id, product_name, category_id) VALUES (223, 'Fitbit Luxe', 6);
INSERT INTO products (id, product_name, category_id) VALUES (224, 'Google Nest Wifi Router', 1);
INSERT INTO products (id, product_name, category_id) VALUES (225, 'Anova Precision Oven', 2);
INSERT INTO products (id, product_name, category_id) VALUES (226, 'Adidas Originals Trefoil Hoodie', 3);
INSERT INTO products (id, product_name, category_id) VALUES (227, 'Fresh Sugar Lip Treatment', 5);
INSERT INTO products (id, product_name, category_id) VALUES (228, 'Hydro Flask Standard Mouth Water Bottle', 6);
INSERT INTO products (id, product_name, category_id) VALUES (229, 'Bose QuietComfort 35 II Wireless Headphones', 1);
INSERT INTO products (id, product_name, category_id) VALUES (230, 'Nespresso Vertuo Next Coffee and Espresso Maker', 2);
INSERT INTO products (id, product_name, category_id) VALUES (231, 'Nike Air Force 1 Sneakers', 3);
INSERT INTO products (id, product_name, category_id) VALUES (232, 'The Handmaid''s Tale by Margaret Atwood', 4);
INSERT INTO products (id, product_name, category_id) VALUES (233, 'Sunday Riley Luna Sleeping Night Oil', 5);
INSERT INTO products (id, product_name, category_id) VALUES (234, 'Yeti Rambler 20 oz Tumbler', 6);
